typer('#path', 70)
    .line('cd users/me/my-kwel-stuff/thingy/this_thingy')
    .line("git checkout development")
    .line("vi scripts.js")
    .line("var makeCoolWebsite = function() {")
    .line("// todo start writing cool stuff")
    .back(5)
    .pause(1000)
    .continue("code")
    .pause(1000)
    .back(9)
    .pause(1000)
    .continue("code")
    .line("}")
    .line("git add .")
    .line("git commit -m 'look ma I m pushing code'")
    .pause("1500")
    .line("git push");